package runner

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/ersinkoc/SimpleDeploy/internal/wizard"
)

const ServiceDir = "/opt/simpledeploy/service"

func InstallService(baseDomain string, webhookPort int) error {
	wizard.Info("Installing SimpleDeploy as a service...")

	if err := os.MkdirAll(ServiceDir, 0755); err != nil {
		return fmt.Errorf("failed to create service directory: %w", err)
	}

	composeContent := generateServiceCompose(baseDomain, webhookPort)
	composePath := filepath.Join(ServiceDir, "docker-compose.yml")
	if err := os.WriteFile(composePath, []byte(composeContent), 0644); err != nil {
		return fmt.Errorf("failed to write service compose: %w", err)
	}

	wizard.Success("Service compose written to " + composePath)
	wizard.Info("Build the image first: docker build -t simpledeploy:latest .")
	wizard.Info("Then start: cd " + ServiceDir + " && docker compose up -d")
	return nil
}

func StartService() error {
	cmd := exec.Command("docker", "compose", "up", "-d")
	cmd.Dir = ServiceDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func StopService() error {
	cmd := exec.Command("docker", "compose", "down")
	cmd.Dir = ServiceDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func generateServiceCompose(baseDomain string, webhookPort int) string {
	return fmt.Sprintf(`# Auto-generated by SimpleDeploy — DO NOT EDIT
# SimpleDeploy Service

services:
  simpledeploy:
    image: simpledeploy:latest
    container_name: qd-service
    restart: unless-stopped
    command: ["webhook", "start", "--port", "%d"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/simpledeploy:/opt/simpledeploy
      - /usr/bin/docker:/usr/bin/docker:ro
    networks:
      - simpledeploy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qd-api.rule=Host(\x60%s\x60) && PathPrefix(\x60/_qd\x60)"
      - "traefik.http.routers.qd-api.entrypoints=websecure"
      - "traefik.http.routers.qd-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.qd-api.loadbalancer.server.port=%d"
`, webhookPort, baseDomain, webhookPort)
}
