package runner

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/ersinkoc/SimpleDeploy/internal/config"
	"github.com/ersinkoc/SimpleDeploy/internal/state"
	"github.com/ersinkoc/SimpleDeploy/internal/wizard"
)

// ServiceDir can be overridden for testing. Defaults to config.BaseDir/service.
var ServiceDir string

func getServiceDir() string {
	if ServiceDir != "" {
		return ServiceDir
	}
	return config.ServiceDir()
}

var (
	osMkdirAll  = os.MkdirAll
	osWriteFile = os.WriteFile
)

func InstallService(baseDomain string, webhookPort int) error {
	// Defense-in-depth: the base domain is interpolated raw into a Traefik
	// Host(`...`) label rule below. init.go validates at the input layer,
	// but a stale or hand-edited state.json could still slip an unsafe
	// value through.
	if err := state.ValidateBaseDomain(baseDomain); err != nil {
		return fmt.Errorf("invalid base domain: %w", err)
	}
	if webhookPort < 1 || webhookPort > 65535 {
		return fmt.Errorf("invalid webhook port %d (must be 1-65535)", webhookPort)
	}

	wizard.Info("Installing SimpleDeploy as a service...")

	if err := osMkdirAll(getServiceDir(), 0755); err != nil {
		return fmt.Errorf("failed to create service directory: %w", err)
	}

	composeContent := generateServiceCompose(baseDomain, webhookPort)
	composePath := filepath.Join(getServiceDir(), "docker-compose.yml")
	if err := osWriteFile(composePath, []byte(composeContent), 0644); err != nil {
		return fmt.Errorf("failed to write service compose: %w", err)
	}

	wizard.Success("Service compose written to " + composePath)
	wizard.Info("Build the image first: docker build -t simpledeploy:latest .")
	wizard.Info("Then start: simpledeploy service start")
	return nil
}

func StartService() error {
	cmd := exec.Command("docker", "compose", "up", "-d")
	cmd.Dir = getServiceDir()
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func StopService() error {
	cmd := exec.Command("docker", "compose", "down")
	cmd.Dir = getServiceDir()
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func generateServiceCompose(baseDomain string, webhookPort int) string {
	// The state directory is resolved on the HOST at install time and mounted
	// at the same path inside the container, with SIMPLEDEPLOY_STATE_DIR
	// pointing at it. Without this the container's $HOME is /root, state.json
	// resolves to an unmounted /root/.simpledeploy/state.json, and the service
	// starts with no apps and no config — the reason `service install`
	// produced a container that immediately exited.
	stateDir := config.HomeDataDir()

	// The Traefik rule is built separately because it needs backticks, and the
	// compose template below is a RAW string literal where `\x60` is not an
	// escape sequence — it is four literal characters. The previous version
	// interpolated `\x60` directly into the template and emitted
	// Host(\x60domain\x60), which Traefik cannot parse, so the service route
	// never worked. Built here with an interpreted string instead.
	const bt = "`"
	traefikRule := fmt.Sprintf("Host(%s%s%s) && PathPrefix(%s/_qd%s)", bt, baseDomain, bt, bt, bt)

	// /etc/machine-id is mounted read-only because state encryption derives its
	// key from the machine ID. A container gets its own, so without this mount
	// every git token and database password written by the host CLI fails to
	// decrypt inside the service and redeploys of private repos break.
	return fmt.Sprintf(`# Auto-generated by SimpleDeploy — DO NOT EDIT
# SimpleDeploy Service

networks:
  simpledeploy:
    name: simpledeploy
    external: true

services:
  simpledeploy:
    image: simpledeploy:latest
    container_name: qd-service
    restart: unless-stopped
    command: ["webhook", "start", "--port", "%d"]
    environment:
      - SIMPLEDEPLOY_DIR=%s
      - SIMPLEDEPLOY_STATE_DIR=%s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - %s:%s
      - %s:%s
      - /etc/machine-id:/etc/machine-id:ro
    ports:
      # Published so the reverse proxy can reach the webhook endpoint at
      # host.docker.internal:<port>, which is the same address it uses when the
      # webhook server runs as a plain host process. One proxy route serves
      # both deployment modes.
      - "%d:%d"
    networks:
      - simpledeploy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qd-api.rule=%s"
      - "traefik.http.routers.qd-api.entrypoints=websecure"
      - "traefik.http.routers.qd-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.qd-api.loadbalancer.server.port=%d"
`,
		webhookPort,
		config.BaseDir,
		stateDir,
		config.BaseDir, config.BaseDir,
		stateDir, stateDir,
		webhookPort, webhookPort,
		traefikRule,
		webhookPort)
}
