package compose

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	cfgpkg "github.com/ersinkoc/SimpleDeploy/internal/config"
	"github.com/ersinkoc/SimpleDeploy/internal/state"
)

type ComposeData struct {
	AppName     string
	Image       string
	Port        int
	Domain      string
	ProxyType   string
	EnvFile     string
	Environment map[string]string
	Databases   []DBService
	Headers     map[string]string
	Repo        string
	Branch      string
	GeneratedAt string
}

type DBService struct {
	Type        string
	Image       string
	Container   string
	Env         map[string]string
	Volume      string
	VolumeName  string
	HealthCheck *HealthCheckData
}

type HealthCheckData struct {
	Test     []string
	Interval string
	Timeout  string
	Retries  int
}

var envKeyRe = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// sortedKeys returns a map's keys in lexical order. Every map walked while
// emitting YAML goes through this so the generated docker-compose.yml is a
// pure function of its inputs — reproducible builds, reviewable diffs, and
// tests that do not depend on Go's randomised map iteration order.
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// yamlQuote returns a YAML-safe double-quoted string.
// It escapes special characters and rejects potentially dangerous sequences
// that could be used for YAML injection attacks.
func yamlQuote(s string) (string, error) {
	escaped := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		"\n", `\n`,
		"\r", `\r`,
		"\t", `\t`,
	).Replace(s)
	return `"` + escaped + `"`, nil
}

func Generate(data *ComposeData) (string, error) {
	// Defense-in-depth: even though deploy.go validates the subdomain and
	// app.go composes the full app domain via state.ValidateAppDomain, the
	// state file itself is plain JSON on disk. A stale state file written
	// before the validators existed, or one tampered with manually, could
	// still slip an unsafe domain through. Block at the point of injection:
	// data.Domain is interpolated unescaped into Traefik Host(`...`) rules
	// below.
	if data.ProxyType == "traefik" {
		if err := state.ValidateAppDomain(data.Domain); err != nil {
			return "", fmt.Errorf("unsafe app domain in compose data: %w", err)
		}
	}

	if err := state.ValidateAppName(data.AppName); err != nil {
		return "", fmt.Errorf("unsafe app name in compose data: %w", err)
	}

	if err := state.ValidateImageTag(data.Image); err != nil {
		return "", fmt.Errorf("unsafe image reference in compose data: %w", err)
	}

	if data.Repo != "" {
		if err := state.ValidateRepoURL(data.Repo); err != nil {
			return "", fmt.Errorf("unsafe repo URL in compose data: %w", err)
		}
	}

	if data.Branch != "" {
		if err := state.ValidateBranch(data.Branch); err != nil {
			return "", fmt.Errorf("unsafe branch in compose data: %w", err)
		}
	}

	// Defense-in-depth on database services: db.Type, db.Image, db.Volume,
	// and db.VolumeName all originate from a static map in db/provisioner.go,
	// but they round-trip through the JSON state file on disk, so a tampered
	// state could otherwise smuggle metacharacters into compose YAML.
	for i, db := range data.Databases {
		if err := state.ValidateDBType(db.Type); err != nil {
			return "", fmt.Errorf("unsafe database[%d] type in compose data: %w", i, err)
		}
		if err := state.ValidateImageTag(db.Image); err != nil {
			return "", fmt.Errorf("unsafe database[%d] image in compose data: %w", i, err)
		}
		if err := state.ValidateContainerPath(db.Volume); err != nil {
			return "", fmt.Errorf("unsafe database[%d] mount path in compose data: %w", i, err)
		}
		if err := state.ValidateVolumeName(db.VolumeName); err != nil {
			return "", fmt.Errorf("unsafe database[%d] volume name in compose data: %w", i, err)
		}
	}

	var b strings.Builder

	b.WriteString("# Auto-generated by SimpleDeploy — DO NOT EDIT\n")
	b.WriteString(fmt.Sprintf("# App: %s | Generated: %s\n\n", data.AppName, data.GeneratedAt))

	b.WriteString("services:\n")

	// Main app service
	b.WriteString(fmt.Sprintf("  %s:\n", data.AppName))
	b.WriteString(fmt.Sprintf("    image: %s\n", data.Image))
	b.WriteString(fmt.Sprintf("    container_name: qd-%s\n", data.AppName))
	b.WriteString("    restart: unless-stopped\n")
	b.WriteString("    networks:\n")
	b.WriteString("      - simpledeploy\n")
	// `expose`, not `ports`. A bare `ports: - "3000"` publishes the container
	// port on a RANDOM host port bound to 0.0.0.0, which means every deployed
	// app was also reachable over plain HTTP directly on the public IP,
	// bypassing the reverse proxy, its TLS termination, and the security
	// headers configured below. The proxy reaches the app over the shared
	// `simpledeploy` bridge network by container name, so no host publishing
	// is needed at all.
	b.WriteString("    expose:\n")
	b.WriteString(fmt.Sprintf("      - \"%d\"\n", data.Port))

	if data.EnvFile != "" {
		b.WriteString(fmt.Sprintf("    env_file:\n      - %s\n", data.EnvFile))
	}

	if len(data.Environment) > 0 {
		b.WriteString("    environment:\n")
		// MAP form ("KEY: \"value\""), not list form ("- KEY=\"value\"").
		//
		// This is load-bearing, not style. In list form the whole item is a
		// single YAML plain scalar, so the quotes yamlQuote adds are NOT YAML
		// syntax — they are literal characters inside the value. Compose splits
		// the item on the first "=" and does no unquoting, so the container
		// received DATABASE_URL as
		//     "postgresql://postgres:pw@qd-app-postgresql:5432/app"
		// with the double quotes included, which no database driver can parse.
		// Every generated variable was affected (DATABASE_URL, REDIS_URL,
		// MONGODB_URI, <TYPE>_URL) as well as every operator-supplied one —
		// NODE_ENV arrived as "production" rather than production.
		//
		// It could not be worked around via the .env file either: `environment`
		// takes precedence over `env_file`, so the correct unquoted value in
		// .env was shadowed by the broken quoted one.
		//
		// In map form the quotes are real YAML quoting and are stripped by the
		// parser, which is why the database services below have always been
		// correct — they used map form all along.
		//
		// Sorted: Go map iteration order is randomised per run, so an unsorted
		// walk produced a different docker-compose.yml on every redeploy even
		// when nothing changed — noisy diffs, and `docker compose up` seeing a
		// "changed" config each time.
		for _, key := range sortedKeys(data.Environment) {
			val := data.Environment[key]
			if !envKeyRe.MatchString(key) {
				return "", fmt.Errorf("invalid environment variable key %q: must match [A-Za-z_][A-Za-z0-9_]*", key)
			}
			quoted, err := yamlQuote(val)
			if err != nil {
				return "", fmt.Errorf("invalid environment variable %s: %w", key, err)
			}
			b.WriteString(fmt.Sprintf("      %s: %s\n", key, quoted))
		}
	}

	if len(data.Databases) > 0 {
		b.WriteString("    depends_on:\n")
		for _, db := range data.Databases {
			if db.HealthCheck != nil {
				b.WriteString(fmt.Sprintf("      qd-%s-%s:\n        condition: service_healthy\n", data.AppName, db.Type))
			} else {
				b.WriteString(fmt.Sprintf("      qd-%s-%s:\n        condition: service_started\n", data.AppName, db.Type))
			}
		}
	}

	// Labels — only emit Traefik labels when using Traefik proxy
	b.WriteString("    labels:\n")
	if data.ProxyType == "traefik" {
		b.WriteString("      - \"traefik.enable=true\"\n")
		b.WriteString(fmt.Sprintf("      - \"traefik.http.routers.%s.rule=Host(`%s`)\"\n", data.AppName, data.Domain))
		b.WriteString(fmt.Sprintf("      - \"traefik.http.routers.%s.entrypoints=websecure\"\n", data.AppName))
		b.WriteString(fmt.Sprintf("      - \"traefik.http.routers.%s.tls.certresolver=letsencrypt\"\n", data.AppName))
		b.WriteString(fmt.Sprintf("      - \"traefik.http.services.%s.loadbalancer.server.port=%d\"\n", data.AppName, data.Port))

		if len(data.Headers) > 0 {
			for _, key := range sortedKeys(data.Headers) {
				val := data.Headers[key]
				if err := state.ValidateHeaderName(key); err != nil {
					return "", fmt.Errorf("invalid header name in compose data: %w", err)
				}
				// The label is wrapped in YAML double quotes; reject control
				// characters in the value rather than escaping, because a
				// CR/LF in a Traefik label is almost always a misconfig and
				// silently escaping it could mask the bug.
				if err := state.ValidateHeaderValue(val); err != nil {
					return "", fmt.Errorf("invalid header value for %q in compose data: %w", key, err)
				}
				b.WriteString(fmt.Sprintf("      - \"traefik.http.middlewares.%s-headers.headers.customresponseheaders.%s=%s\"\n",
					data.AppName, key, val))
			}
			b.WriteString(fmt.Sprintf("      - \"traefik.http.routers.%s.middlewares=%s-headers\"\n", data.AppName, data.AppName))
		}
	}

	// SimpleDeploy metadata labels (always present)
	b.WriteString("      - \"simpledeploy.managed=true\"\n")
	b.WriteString(fmt.Sprintf("      - \"simpledeploy.app=%s\"\n", data.AppName))
	quotedRepo, err := yamlQuote(data.Repo)
	if err != nil {
		return "", fmt.Errorf("invalid repo URL: %w", err)
	}
	b.WriteString(fmt.Sprintf("      - \"simpledeploy.repo=%s\"\n", quotedRepo[1:len(quotedRepo)-1]))
	quotedBranch, err := yamlQuote(data.Branch)
	if err != nil {
		return "", fmt.Errorf("invalid branch name: %w", err)
	}
	b.WriteString(fmt.Sprintf("      - \"simpledeploy.branch=%s\"\n", quotedBranch[1:len(quotedBranch)-1]))

	// Database services
	for _, db := range data.Databases {
		b.WriteString("\n")
		b.WriteString(fmt.Sprintf("  qd-%s-%s:\n", data.AppName, db.Type))
		b.WriteString(fmt.Sprintf("    image: %s\n", db.Image))
		b.WriteString(fmt.Sprintf("    container_name: qd-%s-%s\n", data.AppName, db.Type))
		b.WriteString("    restart: unless-stopped\n")
		b.WriteString("    networks:\n      - simpledeploy\n")

		if len(db.Env) > 0 {
			b.WriteString("    environment:\n")
			for _, key := range sortedKeys(db.Env) {
				val := db.Env[key]
				quoted, err := yamlQuote(val)
				if err != nil {
					return "", fmt.Errorf("invalid database environment variable %s: %w", key, err)
				}
				b.WriteString(fmt.Sprintf("      %s: %s\n", key, quoted))
			}
		}

		b.WriteString(fmt.Sprintf("    volumes:\n      - %s:%s\n", db.VolumeName, db.Volume))

		if db.HealthCheck != nil {
			b.WriteString("    healthcheck:\n")
			parts := make([]string, len(db.HealthCheck.Test))
			for i, t := range db.HealthCheck.Test {
				parts[i] = fmt.Sprintf("%q", t)
			}
			b.WriteString(fmt.Sprintf("      test: [%s]\n", strings.Join(parts, ", ")))
			b.WriteString(fmt.Sprintf("      interval: %s\n", db.HealthCheck.Interval))
			b.WriteString(fmt.Sprintf("      timeout: %s\n", db.HealthCheck.Timeout))
			b.WriteString(fmt.Sprintf("      retries: %d\n", db.HealthCheck.Retries))
		}
	}

	// Networks
	b.WriteString("\nnetworks:\n  simpledeploy:\n    external: true\n")

	// Volumes
	if len(data.Databases) > 0 {
		b.WriteString("\nvolumes:\n")
		for _, db := range data.Databases {
			b.WriteString(fmt.Sprintf("  %s:\n", db.VolumeName))
		}
	}

	return b.String(), nil
}

func WriteCompose(appDir string, content string) error {
	if err := os.MkdirAll(appDir, 0755); err != nil {
		return fmt.Errorf("failed to create app directory: %w", err)
	}
	// 0600 because the generated compose file embeds the database root passwords
	// directly under each db service's `environment:` block (see Generate above
	// — db.Env is populated from app.DBCredentials at deploy time and lands in
	// the YAML in plaintext). Read by the user running docker compose, which is
	// the same user that simpledeploy runs as, so 0600 is sufficient.
	return os.WriteFile(filepath.Join(appDir, "docker-compose.yml"), []byte(content), 0600)
}

func NewComposeData(app *state.AppConfig, cfg *state.GlobalConfig) *ComposeData {
	return &ComposeData{
		AppName:     app.Name,
		Image:       app.CurrentImage,
		Port:        app.Port,
		Domain:      app.Domain,
		ProxyType:   cfg.Proxy,
		EnvFile:     filepath.Join(cfgpkg.AppDir(app.Name), ".env"),
		Environment: make(map[string]string),
		Databases:   []DBService{},
		Headers:     app.Headers,
		Repo:        app.Repo,
		Branch:      app.Branch,
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
	}
}
