package compose

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/ersinkoc/SimpleDeploy/internal/state"
)

func TestGenerateBasic(t *testing.T) {
	data := &ComposeData{
		AppName:     "myapp",
		Image:       "myapp:latest",
		Port:        3000,
		Domain:      "myapp.example.com",
		ProxyType:   "traefik",
		EnvFile:     "/opt/simpledeploy/apps/myapp/.env",
		Environment: map[string]string{"KEY": "value"},
		Databases:   nil,
		Headers:     map[string]string{"X-Custom": "yes"},
		Repo:        "https://github.com/test/myapp.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml, err := Generate(data)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	if !strings.Contains(yaml, "# Auto-generated by SimpleDeploy") {
		t.Error("Should contain auto-generated header")
	}
	if !strings.Contains(yaml, "container_name: qd-myapp") {
		t.Error("Should contain container name")
	}
	if !strings.Contains(yaml, "image: myapp:latest") {
		t.Error("Should contain image")
	}
	if !strings.Contains(yaml, "simpledeploy:") {
		t.Error("Should use simpledeploy network")
	}
	if !strings.Contains(yaml, "traefik.enable=true") {
		t.Error("Should contain traefik labels")
	}
	if !strings.Contains(yaml, "Host(`myapp.example.com`)") {
		t.Error("Should contain domain rule")
	}
	if !strings.Contains(yaml, `KEY="value"`) {
		t.Error("Should contain environment variable")
	}
	if !strings.Contains(yaml, "X-Custom=yes") {
		t.Error("Should contain custom header")
	}
	if !strings.Contains(yaml, "simpledeploy.managed=true") {
		t.Error("Should contain metadata label")
	}
}

func TestGenerateWithDatabases(t *testing.T) {
	data := &ComposeData{
		AppName:   "dbapp",
		Image:     "dbapp:v1",
		Port:      8080,
		Domain:    "dbapp.example.com",
		ProxyType: "traefik",
		Databases: []DBService{
			{
				Type:       "mysql",
				Image:      "mysql:8",
				Container:  "mysql",
				Volume:     "/var/lib/mysql",
				VolumeName: "qd-dbapp-mysql-data",
				Env:        map[string]string{"MYSQL_ROOT_PASSWORD": "secret", "MYSQL_DATABASE": "dbapp"},
				HealthCheck: &HealthCheckData{
					Test:     []string{"CMD", "mysqladmin", "ping", "-h", "localhost"},
					Interval: "10s",
					Timeout:  "5s",
					Retries:  5,
				},
			},
			{
				Type:       "redis",
				Image:      "redis:7-alpine",
				Container:  "redis",
				Volume:     "/data",
				VolumeName: "qd-dbapp-redis-data",
				Env:        map[string]string{},
			},
		},
		Headers:     map[string]string{},
		Repo:        "https://github.com/test/dbapp.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml, err := Generate(data)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	if !strings.Contains(yaml, "qd-dbapp-mysql") {
		t.Error("Should contain mysql service")
	}
	if !strings.Contains(yaml, "mysql:8") {
		t.Error("Should contain mysql image")
	}
	if !strings.Contains(yaml, `MYSQL_ROOT_PASSWORD: "secret"`) {
		t.Error("Should contain mysql password")
	}
	if !strings.Contains(yaml, "healthcheck:") {
		t.Error("Should contain healthcheck")
	}
	if !strings.Contains(yaml, "mysqladmin") {
		t.Error("Should contain healthcheck test")
	}
	if !strings.Contains(yaml, "qd-dbapp-redis") {
		t.Error("Should contain redis service")
	}
	if !strings.Contains(yaml, "service_healthy") {
		t.Error("Should depend on healthy mysql")
	}
	if !strings.Contains(yaml, "qd-dbapp-mysql-data:") {
		t.Error("Should contain volume declarations")
	}
}

func TestGenerateCaddyProxyNoTraefikLabels(t *testing.T) {
	data := &ComposeData{
		AppName:     "caddyapp",
		Image:       "caddyapp:v1",
		Port:        8080,
		Domain:      "caddyapp.example.com",
		ProxyType:   "caddy",
		Headers:     map[string]string{},
		Repo:        "https://github.com/test/app.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml, err := Generate(data)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	if strings.Contains(yaml, "traefik.enable=true") {
		t.Error("Caddy mode should NOT emit traefik labels")
	}
	if !strings.Contains(yaml, "simpledeploy.managed=true") {
		t.Error("Should still contain metadata labels")
	}
}

func TestGenerateNoEnvFile(t *testing.T) {
	data := &ComposeData{
		AppName:     "noenv",
		Image:       "noenv:v1",
		Port:        3000,
		Domain:      "noenv.example.com",
		ProxyType:   "traefik",
		EnvFile:     "",
		Environment: map[string]string{},
		Headers:     map[string]string{},
		Repo:        "https://github.com/test/app.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml, err := Generate(data)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	if strings.Contains(yaml, "env_file:") {
		t.Error("Should not contain env_file when empty")
	}
}

func TestNewComposeData(t *testing.T) {
	app := &state.AppConfig{
		Name:         "testapp",
		Repo:         "https://github.com/test/app.git",
		Branch:       "develop",
		Port:         4000,
		Domain:       "test.example.com",
		CurrentImage: "testapp:v2",
		Headers:      map[string]string{"X-Test": "yes"},
	}
	cfg := &state.GlobalConfig{
		Proxy: "traefik",
	}

	data := NewComposeData(app, cfg)

	if data.AppName != "testapp" {
		t.Errorf("AppName = %q, want 'testapp'", data.AppName)
	}
	if data.ProxyType != "traefik" {
		t.Errorf("ProxyType = %q, want 'traefik'", data.ProxyType)
	}
	if data.Port != 4000 {
		t.Errorf("Port = %d, want 4000", data.Port)
	}
}

func TestWriteCompose(t *testing.T) {
	dir := t.TempDir()
	content := "services:\n  test:\n    image: test\n"
	if err := WriteCompose(dir, content); err != nil {
		t.Fatalf("WriteCompose failed: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "docker-compose.yml"))
	if err != nil {
		t.Fatalf("ReadFile failed: %v", err)
	}
	if string(data) != content {
		t.Errorf("Written content doesn't match")
	}
}

// TestWriteCompose_Mode0600 confirms the generated docker-compose.yml is
// written with owner-only perms — the YAML embeds DB root passwords directly
// in the database services' environment block, so a world-readable file
// would leak credentials to other users on the host. Skipped on Windows
// because Go's os.FileMode does not faithfully reflect Windows ACLs.
func TestWriteCompose_Mode0600(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("file modes are not POSIX on Windows")
	}
	dir := t.TempDir()
	if err := WriteCompose(dir, "services: {}\n"); err != nil {
		t.Fatalf("WriteCompose failed: %v", err)
	}
	info, err := os.Stat(filepath.Join(dir, "docker-compose.yml"))
	if err != nil {
		t.Fatalf("Stat failed: %v", err)
	}
	if got := info.Mode().Perm(); got != 0600 {
		t.Errorf("docker-compose.yml mode = %#o, want 0600 — file may carry DB credentials", got)
	}
}

func TestWriteComposeCreatesDir(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "nested", "dir")
	content := "test: true\n"
	if err := WriteCompose(dir, content); err != nil {
		t.Fatalf("WriteCompose failed for nested dir: %v", err)
	}
	data, _ := os.ReadFile(filepath.Join(dir, "docker-compose.yml"))
	if string(data) != content {
		t.Error("Content mismatch")
	}
}

func TestGenerateEmptyDatabases(t *testing.T) {
	data := &ComposeData{
		AppName:     "simple",
		Image:       "simple:v1",
		Port:        80,
		Domain:      "simple.example.com",
		ProxyType:   "traefik",
		Environment: map[string]string{},
		Headers:     map[string]string{},
		Repo:        "https://github.com/test/app.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml, err := Generate(data)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	if strings.Contains(yaml, "volumes:") {
		// The network section has no volumes: prefix
		if strings.Count(yaml, "volumes:") > 0 {
			lines := strings.Split(yaml, "\n")
			for _, line := range lines {
				if strings.HasPrefix(strings.TrimSpace(line), "volumes:") {
					t.Error("Should not have volumes section when no databases")
				}
			}
		}
	}
	if strings.Contains(yaml, "depends_on:") {
		t.Error("Should not have depends_on when no databases")
	}
}

func TestGenerate_DBWithoutHealthCheck(t *testing.T) {
	data := &ComposeData{
		AppName:   "redisapp",
		Image:     "redisapp:v1",
		Port:      3000,
		Domain:    "redisapp.example.com",
		ProxyType: "traefik",
		Databases: []DBService{
			{
				Type:       "redis",
				Image:      "redis:7-alpine",
				Container:  "redis",
				Volume:     "/data",
				VolumeName: "qd-redisapp-redis-data",
				Env:        map[string]string{},
			},
		},
		Headers:     map[string]string{},
		Repo:        "https://github.com/test/app.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml, err := Generate(data)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	if !strings.Contains(yaml, "service_started") {
		t.Error("DB without health check should use service_started condition")
	}
}

func TestGenerate_MultipleEnvVars(t *testing.T) {
	data := &ComposeData{
		AppName:     "envapp",
		Image:       "envapp:v1",
		Port:        3000,
		Domain:      "envapp.example.com",
		ProxyType:   "traefik",
		Environment: map[string]string{"DB_HOST": "db", "DB_PORT": "5432", "DEBUG": "false"},
		Headers:     map[string]string{},
		Repo:        "https://github.com/test/app.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml, err := Generate(data)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	for k, v := range data.Environment {
		expected := k + "=\"" + v + "\""
		if !strings.Contains(yaml, expected) {
			t.Errorf("Should contain env var %s", expected)
		}
	}
}

func TestGenerate_CaddyWithHeaders(t *testing.T) {
	data := &ComposeData{
		AppName:     "caddyapp2",
		Image:       "caddyapp2:v1",
		Port:        8080,
		Domain:      "caddyapp2.example.com",
		ProxyType:   "caddy",
		Headers:     map[string]string{"X-Custom": "value"},
		Repo:        "https://github.com/test/app.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml, err := Generate(data)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	// Caddy mode should not have traefik headers middleware
	if strings.Contains(yaml, "traefik.http.middlewares") {
		t.Error("Caddy mode should not emit traefik middlewares")
	}
}

func TestWriteCompose_InvalidPath(t *testing.T) {
	// Create a read-only file and try to use it as a directory
	tmpFile := filepath.Join(t.TempDir(), "readonly-file")
	os.WriteFile(tmpFile, []byte("x"), 0444)

	// Try to write compose into the file (can't create dir inside a file)
	err := WriteCompose(tmpFile+"/nested/dir", "test: true\n")
	if err == nil {
		t.Skip("Platform allows writing into file paths")
	}
}

func TestGenerate_TraefikWithHeaders(t *testing.T) {
	data := &ComposeData{
		AppName:     "hdrapp",
		Image:       "hdrapp:v1",
		Port:        3000,
		Domain:      "hdrapp.example.com",
		ProxyType:   "traefik",
		Headers:     map[string]string{"X-Frame-Options": "DENY", "X-Custom": "value"},
		Repo:        "https://github.com/test/app.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml, err := Generate(data)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	if !strings.Contains(yaml, "traefik.http.middlewares.hdrapp-headers") {
		t.Error("Should contain headers middleware")
	}
	if !strings.Contains(yaml, "X-Frame-Options=DENY") {
		t.Error("Should contain X-Frame-Options header")
	}
	if !strings.Contains(yaml, "routers.hdrapp.middlewares=hdrapp-headers") {
		t.Error("Should apply headers middleware to router")
	}
}

func TestGenerate_EnvFile(t *testing.T) {
	data := &ComposeData{
		AppName:     "envapp",
		Image:       "envapp:v1",
		Port:        3000,
		Domain:      "envapp.example.com",
		ProxyType:   "traefik",
		EnvFile:     "/opt/simpledeploy/apps/envapp/.env",
		Repo:        "https://github.com/test/app.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml, err := Generate(data)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	if !strings.Contains(yaml, "env_file:") {
		t.Error("Should contain env_file directive")
	}
	if !strings.Contains(yaml, "/opt/simpledeploy/apps/envapp/.env") {
		t.Error("Should contain env file path")
	}
}

func TestNewComposeData_SetsFields(t *testing.T) {
	app := &state.AppConfig{
		Name:         "myapp",
		Repo:         "https://github.com/test/myapp.git",
		Branch:       "develop",
		Port:         5000,
		Domain:       "myapp.test.com",
		CurrentImage: "myapp:latest",
		Headers:      map[string]string{"X-App": "test"},
	}
	cfg := &state.GlobalConfig{Proxy: "caddy"}

	data := NewComposeData(app, cfg)

	if data.Image != "myapp:latest" {
		t.Errorf("Image = %q, want 'myapp:latest'", data.Image)
	}
	if data.Domain != "myapp.test.com" {
		t.Errorf("Domain = %q, want 'myapp.test.com'", data.Domain)
	}
	if data.EnvFile == "" {
		t.Error("EnvFile should be set")
	}
	if len(data.Environment) != 0 {
		t.Error("Environment should start empty")
	}
	if len(data.Databases) != 0 {
		t.Error("Databases should start empty")
	}
}

// TestYAMLQuote_Security tests that yamlQuote rejects potentially dangerous sequences
// that could be used for YAML injection attacks.
func TestYAMLQuote_Security(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		wantErr  bool
		contains string
	}{
		{
			name:     "Normal value",
			input:    "hello world",
			contains: `"hello world"`,
		},
		{
			name:     "Value with interpolation",
			input:    "${ENV_VAR}",
			contains: `"${ENV_VAR}"`,
		},
		{
			name:     "Value with comment",
			input:    "value # comment",
			contains: `"value # comment"`,
		},
		{
			name:     "Value starting with dash",
			input:    "- malicious",
			contains: `"- malicious"`,
		},
		{
			name:     "Value with double quotes",
			input:    `value "quoted"`,
			contains: `"value \"quoted\""`,
		},
		{
			name:     "Value with backslash",
			input:    `path\to\file`,
			contains: `"path\\to\\file"`,
		},
		{
			name:     "Value with newline",
			input:    "line1\nline2",
			contains: `"line1\nline2"`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result, err := yamlQuote(tt.input)
			if tt.wantErr && err == nil {
				t.Errorf("yamlQuote(%q) expected error, got nil", tt.input)
			}
			if !tt.wantErr && err != nil {
				t.Errorf("yamlQuote(%q) expected no error, got: %v", tt.input, err)
			}
			if !tt.wantErr && result != tt.contains {
				t.Errorf("yamlQuote(%q) = %q, want %q", tt.input, result, tt.contains)
			}
		})
	}
}

// TestGenerate_YAMLInjectionProtection tests that Generate rejects environment variables
// containing YAML injection sequences.
func TestGenerate_YAMLInjectionProtection(t *testing.T) {
	data := &ComposeData{
		AppName:     "testapp",
		Image:       "test:v1",
		Port:        3000,
		Domain:      "test.example.com",
		ProxyType:   "traefik",
		Environment: map[string]string{"MALICIOUS": "${PATH}"},
		Headers:     map[string]string{},
		Repo:        "https://github.com/test/test.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	_, err := Generate(data)
	if err != nil {
		t.Errorf("Generate should escape YAML injection sequences, not reject: %v", err)
	}
}
