package compose

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ersinkoc/SimpleDeploy/internal/state"
)

func TestGenerateBasic(t *testing.T) {
	data := &ComposeData{
		AppName:     "myapp",
		Image:       "myapp:latest",
		Port:        3000,
		Domain:      "myapp.example.com",
		ProxyType:   "traefik",
		EnvFile:     "/opt/simpledeploy/apps/myapp/.env",
		Environment: map[string]string{"KEY": "value"},
		Databases:   nil,
		Headers:     map[string]string{"X-Custom": "yes"},
		Repo:        "https://github.com/test/myapp.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml := Generate(data)

	if !strings.Contains(yaml, "# Auto-generated by SimpleDeploy") {
		t.Error("Should contain auto-generated header")
	}
	if !strings.Contains(yaml, "container_name: qd-myapp") {
		t.Error("Should contain container name")
	}
	if !strings.Contains(yaml, "image: myapp:latest") {
		t.Error("Should contain image")
	}
	if !strings.Contains(yaml, "simpledeploy:") {
		t.Error("Should use simpledeploy network")
	}
	if !strings.Contains(yaml, "traefik.enable=true") {
		t.Error("Should contain traefik labels")
	}
	if !strings.Contains(yaml, "Host(`myapp.example.com`)") {
		t.Error("Should contain domain rule")
	}
	if !strings.Contains(yaml, "KEY=value") {
		t.Error("Should contain environment variable")
	}
	if !strings.Contains(yaml, "X-Custom=yes") {
		t.Error("Should contain custom header")
	}
	if !strings.Contains(yaml, "simpledeploy.managed=true") {
		t.Error("Should contain metadata label")
	}
}

func TestGenerateWithDatabases(t *testing.T) {
	data := &ComposeData{
		AppName:   "dbapp",
		Image:     "dbapp:v1",
		Port:      8080,
		Domain:    "dbapp.example.com",
		ProxyType: "traefik",
		Databases: []DBService{
			{
				Type:       "mysql",
				Image:      "mysql:8",
				Container:  "mysql",
				Volume:     "/var/lib/mysql",
				VolumeName: "qd-dbapp-mysql-data",
				Env:        map[string]string{"MYSQL_ROOT_PASSWORD": "secret", "MYSQL_DATABASE": "dbapp"},
				HealthCheck: &HealthCheckData{
					Test:     []string{"CMD", "mysqladmin", "ping", "-h", "localhost"},
					Interval: "10s",
					Timeout:  "5s",
					Retries:  5,
				},
			},
			{
				Type:       "redis",
				Image:      "redis:7-alpine",
				Container:  "redis",
				Volume:     "/data",
				VolumeName: "qd-dbapp-redis-data",
				Env:        map[string]string{},
			},
		},
		Headers:     map[string]string{},
		Repo:        "https://github.com/test/dbapp.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml := Generate(data)

	if !strings.Contains(yaml, "qd-dbapp-mysql") {
		t.Error("Should contain mysql service")
	}
	if !strings.Contains(yaml, "mysql:8") {
		t.Error("Should contain mysql image")
	}
	if !strings.Contains(yaml, "MYSQL_ROOT_PASSWORD: secret") {
		t.Error("Should contain mysql password")
	}
	if !strings.Contains(yaml, "healthcheck:") {
		t.Error("Should contain healthcheck")
	}
	if !strings.Contains(yaml, "mysqladmin") {
		t.Error("Should contain healthcheck test")
	}
	if !strings.Contains(yaml, "qd-dbapp-redis") {
		t.Error("Should contain redis service")
	}
	if !strings.Contains(yaml, "service_healthy") {
		t.Error("Should depend on healthy mysql")
	}
	if !strings.Contains(yaml, "qd-dbapp-mysql-data:") {
		t.Error("Should contain volume declarations")
	}
}

func TestGenerateCaddyProxyNoTraefikLabels(t *testing.T) {
	data := &ComposeData{
		AppName:     "caddyapp",
		Image:       "caddyapp:v1",
		Port:        8080,
		Domain:      "caddyapp.example.com",
		ProxyType:   "caddy",
		Headers:     map[string]string{},
		Repo:        "https://github.com/test/app.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml := Generate(data)

	if strings.Contains(yaml, "traefik.enable=true") {
		t.Error("Caddy mode should NOT emit traefik labels")
	}
	if !strings.Contains(yaml, "simpledeploy.managed=true") {
		t.Error("Should still contain metadata labels")
	}
}

func TestGenerateNoEnvFile(t *testing.T) {
	data := &ComposeData{
		AppName:     "noenv",
		Image:       "noenv:v1",
		Port:        3000,
		Domain:      "noenv.example.com",
		ProxyType:   "traefik",
		EnvFile:     "",
		Environment: map[string]string{},
		Headers:     map[string]string{},
		Repo:        "https://github.com/test/app.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml := Generate(data)
	if strings.Contains(yaml, "env_file:") {
		t.Error("Should not contain env_file when empty")
	}
}

func TestNewComposeData(t *testing.T) {
	app := &state.AppConfig{
		Name:         "testapp",
		Repo:         "https://github.com/test/app.git",
		Branch:       "develop",
		Port:         4000,
		Domain:       "test.example.com",
		CurrentImage: "testapp:v2",
		Headers:      map[string]string{"X-Test": "yes"},
	}
	cfg := &state.GlobalConfig{
		Proxy: "traefik",
	}

	data := NewComposeData(app, cfg)

	if data.AppName != "testapp" {
		t.Errorf("AppName = %q, want 'testapp'", data.AppName)
	}
	if data.ProxyType != "traefik" {
		t.Errorf("ProxyType = %q, want 'traefik'", data.ProxyType)
	}
	if data.Port != 4000 {
		t.Errorf("Port = %d, want 4000", data.Port)
	}
}

func TestWriteCompose(t *testing.T) {
	dir := t.TempDir()
	content := "services:\n  test:\n    image: test\n"
	if err := WriteCompose(dir, content); err != nil {
		t.Fatalf("WriteCompose failed: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "docker-compose.yml"))
	if err != nil {
		t.Fatalf("ReadFile failed: %v", err)
	}
	if string(data) != content {
		t.Errorf("Written content doesn't match")
	}
}

func TestWriteComposeCreatesDir(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "nested", "dir")
	content := "test: true\n"
	if err := WriteCompose(dir, content); err != nil {
		t.Fatalf("WriteCompose failed for nested dir: %v", err)
	}
	data, _ := os.ReadFile(filepath.Join(dir, "docker-compose.yml"))
	if string(data) != content {
		t.Error("Content mismatch")
	}
}

func TestGenerateEmptyDatabases(t *testing.T) {
	data := &ComposeData{
		AppName:     "simple",
		Image:       "simple:v1",
		Port:        80,
		Domain:      "simple.example.com",
		ProxyType:   "traefik",
		Environment: map[string]string{},
		Headers:     map[string]string{},
		Repo:        "https://github.com/test/app.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml := Generate(data)
	if strings.Contains(yaml, "volumes:") {
		// The network section has no volumes: prefix
		if strings.Count(yaml, "volumes:") > 0 {
			lines := strings.Split(yaml, "\n")
			for _, line := range lines {
				if strings.HasPrefix(strings.TrimSpace(line), "volumes:") {
					t.Error("Should not have volumes section when no databases")
				}
			}
		}
	}
	if strings.Contains(yaml, "depends_on:") {
		t.Error("Should not have depends_on when no databases")
	}
}

func TestGenerate_DBWithoutHealthCheck(t *testing.T) {
	data := &ComposeData{
		AppName:   "redisapp",
		Image:     "redisapp:v1",
		Port:      3000,
		Domain:    "redisapp.example.com",
		ProxyType: "traefik",
		Databases: []DBService{
			{
				Type:       "redis",
				Image:      "redis:7-alpine",
				Container:  "redis",
				Volume:     "/data",
				VolumeName: "qd-redisapp-redis-data",
				Env:        map[string]string{},
			},
		},
		Headers:     map[string]string{},
		Repo:        "https://github.com/test/app.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml := Generate(data)
	if !strings.Contains(yaml, "service_started") {
		t.Error("DB without health check should use service_started condition")
	}
}

func TestGenerate_MultipleEnvVars(t *testing.T) {
	data := &ComposeData{
		AppName:     "envapp",
		Image:       "envapp:v1",
		Port:        3000,
		Domain:      "envapp.example.com",
		ProxyType:   "traefik",
		Environment: map[string]string{"DB_HOST": "db", "DB_PORT": "5432", "DEBUG": "false"},
		Headers:     map[string]string{},
		Repo:        "https://github.com/test/app.git",
		Branch:      "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml := Generate(data)
	for k, v := range data.Environment {
		expected := k + "=" + v
		if !strings.Contains(yaml, expected) {
			t.Errorf("Should contain env var %s", expected)
		}
	}
}

func TestGenerate_CaddyWithHeaders(t *testing.T) {
	data := &ComposeData{
		AppName:   "caddyapp2",
		Image:     "caddyapp2:v1",
		Port:      8080,
		Domain:    "caddyapp2.example.com",
		ProxyType: "caddy",
		Headers:   map[string]string{"X-Custom": "value"},
		Repo:      "https://github.com/test/app.git",
		Branch:    "main",
		GeneratedAt: "2024-01-15T10:30:00Z",
	}

	yaml := Generate(data)
	// Caddy mode should not have traefik headers middleware
	if strings.Contains(yaml, "traefik.http.middlewares") {
		t.Error("Caddy mode should not emit traefik middlewares")
	}
}

func TestNewComposeData_SetsFields(t *testing.T) {
	app := &state.AppConfig{
		Name:         "myapp",
		Repo:         "https://github.com/test/myapp.git",
		Branch:       "develop",
		Port:         5000,
		Domain:       "myapp.test.com",
		CurrentImage: "myapp:latest",
		Headers:      map[string]string{"X-App": "test"},
	}
	cfg := &state.GlobalConfig{Proxy: "caddy"}

	data := NewComposeData(app, cfg)

	if data.Image != "myapp:latest" {
		t.Errorf("Image = %q, want 'myapp:latest'", data.Image)
	}
	if data.Domain != "myapp.test.com" {
		t.Errorf("Domain = %q, want 'myapp.test.com'", data.Domain)
	}
	if data.EnvFile == "" {
		t.Error("EnvFile should be set")
	}
	if len(data.Environment) != 0 {
		t.Error("Environment should start empty")
	}
	if len(data.Databases) != 0 {
		t.Error("Databases should start empty")
	}
}
