package compose

// TraefikTemplate is the reference Traefik compose template.
var TraefikTemplate = `# Auto-generated by SimpleDeploy — DO NOT EDIT
# Reverse Proxy: Traefik

networks:
  simpledeploy:
    name: simpledeploy

services:
  traefik:
    image: traefik:v3
    container_name: qd-traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=simpledeploy"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--certificatesresolvers.letsencrypt.acme.email={{.AcmeEmail}}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - qd-letsencrypt:/letsencrypt
    networks:
      - simpledeploy

volumes:
  qd-letsencrypt:
`

// CaddyTemplate is the reference Caddy compose template.
var CaddyTemplate = `# Auto-generated by SimpleDeploy — DO NOT EDIT
# Reverse Proxy: Caddy

networks:
  simpledeploy:
    name: simpledeploy

services:
  caddy:
    image: caddy:2-alpine
    container_name: qd-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - qd-caddy-data:/data
      - qd-caddy-config:/config
    networks:
      - simpledeploy

volumes:
  qd-caddy-data:
  qd-caddy-config:
`
