package proxy

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/ersinkoc/SimpleDeploy/internal/docker"
	"github.com/ersinkoc/SimpleDeploy/internal/wizard"
)

func SetupCaddy(acmeEmail string) error {
	wizard.Info("Setting up Caddy reverse proxy...")

	if err := os.MkdirAll(ProxyDir, 0755); err != nil {
		return fmt.Errorf("failed to create proxy directory: %w", err)
	}

	composeContent := generateCaddyCompose()
	composePath := filepath.Join(ProxyDir, "docker-compose.yml")
	if err := os.WriteFile(composePath, []byte(composeContent), 0644); err != nil {
		return fmt.Errorf("failed to write Caddy compose: %w", err)
	}

	caddyfile := fmt.Sprintf("{\n    email %s\n}\n", acmeEmail)
	caddyfilePath := filepath.Join(ProxyDir, "Caddyfile")
	if err := os.WriteFile(caddyfilePath, []byte(caddyfile), 0644); err != nil {
		return fmt.Errorf("failed to write Caddyfile: %w", err)
	}

	if err := docker.CreateNetwork("simpledeploy"); err != nil {
		return err
	}

	cmd := exec.Command("docker", "compose", "up", "-d")
	cmd.Dir = ProxyDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to start Caddy: %w", err)
	}

	wizard.Success("Caddy reverse proxy started")
	return nil
}

func AddCaddyApp(appName, domain string, port int, headers map[string]string) error {
	caddyfilePath := filepath.Join(ProxyDir, "Caddyfile")
	data, err := os.ReadFile(caddyfilePath)
	if err != nil {
		return fmt.Errorf("failed to read Caddyfile: %w", err)
	}

	var b strings.Builder
	b.WriteString(string(data))
	b.WriteString(fmt.Sprintf("\n%s {\n", domain))
	b.WriteString(fmt.Sprintf("    reverse_proxy qd-%s:%d\n", appName, port))
	for key, val := range headers {
		b.WriteString(fmt.Sprintf("    header %s \"%s\"\n", key, val))
	}
	b.WriteString("}\n")

	return os.WriteFile(caddyfilePath, []byte(b.String()), 0644)
}

func RemoveCaddyApp(domain string) error {
	caddyfilePath := filepath.Join(ProxyDir, "Caddyfile")
	data, err := os.ReadFile(caddyfilePath)
	if err != nil {
		return err
	}

	lines := strings.Split(string(data), "\n")
	var result []string
	skip := false
	for _, line := range lines {
		if strings.TrimSpace(line) == domain+" {" {
			skip = true
			continue
		}
		if skip && strings.TrimSpace(line) == "}" {
			skip = false
			continue
		}
		if !skip {
			result = append(result, line)
		}
	}

	return os.WriteFile(caddyfilePath, []byte(strings.Join(result, "\n")), 0644)
}

func ReloadCaddy() error {
	cmd := exec.Command("docker", "exec", "qd-caddy", "caddy", "reload", "--config", "/etc/caddy/Caddyfile")
	return cmd.Run()
}

func StopCaddy() error {
	cmd := exec.Command("docker", "compose", "down")
	cmd.Dir = ProxyDir
	return cmd.Run()
}

func generateCaddyCompose() string {
	return `# Auto-generated by SimpleDeploy — DO NOT EDIT
# Reverse Proxy: Caddy

networks:
  simpledeploy:
    name: simpledeploy
    external: true

services:
  caddy:
    image: caddy:2-alpine
    container_name: qd-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - qd-caddy-data:/data
      - qd-caddy-config:/config
    networks:
      - simpledeploy

volumes:
  qd-caddy-data:
  qd-caddy-config:
`
}
