package proxy

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/ersinkoc/SimpleDeploy/internal/docker"
	"github.com/ersinkoc/SimpleDeploy/internal/wizard"
)

const ProxyDir = "/opt/simpledeploy/proxy"

func SetupTraefik(acmeEmail string) error {
	wizard.Info("Setting up Traefik reverse proxy...")

	if err := os.MkdirAll(ProxyDir, 0755); err != nil {
		return fmt.Errorf("failed to create proxy directory: %w", err)
	}

	composeContent := generateTraefikCompose(acmeEmail)
	composePath := filepath.Join(ProxyDir, "docker-compose.yml")

	if err := os.WriteFile(composePath, []byte(composeContent), 0644); err != nil {
		return fmt.Errorf("failed to write Traefik compose: %w", err)
	}

	// Write .env for ACME email
	envPath := filepath.Join(ProxyDir, ".env")
	envContent := fmt.Sprintf("ACME_EMAIL=%s\n", acmeEmail)
	if err := os.WriteFile(envPath, []byte(envContent), 0644); err != nil {
		return fmt.Errorf("failed to write proxy .env: %w", err)
	}

	// Ensure network exists
	if err := docker.CreateNetwork("simpledeploy"); err != nil {
		return err
	}

	// Start Traefik
	cmd := exec.Command("docker", "compose", "up", "-d")
	cmd.Dir = ProxyDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to start Traefik: %w", err)
	}

	wizard.Success("Traefik reverse proxy started")
	return nil
}

func StopTraefik() error {
	cmd := exec.Command("docker", "compose", "down")
	cmd.Dir = ProxyDir
	return cmd.Run()
}

func RestartTraefik() error {
	cmd := exec.Command("docker", "compose", "restart")
	cmd.Dir = ProxyDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func generateTraefikCompose(acmeEmail string) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by SimpleDeploy — DO NOT EDIT\n")
	b.WriteString("# Reverse Proxy: Traefik\n\n")
	b.WriteString("networks:\n  simpledeploy:\n    name: simpledeploy\n\n")
	b.WriteString("services:\n  traefik:\n")
	b.WriteString("    image: traefik:v3\n")
	b.WriteString("    container_name: qd-traefik\n")
	b.WriteString("    restart: unless-stopped\n")
	b.WriteString("    command:\n")
	b.WriteString("      - \"--api.dashboard=false\"\n")
	b.WriteString("      - \"--providers.docker=true\"\n")
	b.WriteString("      - \"--providers.docker.exposedbydefault=false\"\n")
	b.WriteString("      - \"--providers.docker.network=simpledeploy\"\n")
	b.WriteString("      - \"--entrypoints.web.address=:80\"\n")
	b.WriteString("      - \"--entrypoints.websecure.address=:443\"\n")
	b.WriteString("      - \"--entrypoints.web.http.redirections.entryPoint.to=websecure\"\n")
	b.WriteString(fmt.Sprintf("      - \"--certificatesresolvers.letsencrypt.acme.email=%s\"\n", acmeEmail))
	b.WriteString("      - \"--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json\"\n")
	b.WriteString("      - \"--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web\"\n")
	b.WriteString("    ports:\n      - \"80:80\"\n      - \"443:443\"\n")
	b.WriteString("    volumes:\n")
	b.WriteString("      - /var/run/docker.sock:/var/run/docker.sock:ro\n")
	b.WriteString("      - qd-letsencrypt:/letsencrypt\n")
	b.WriteString("    networks:\n      - simpledeploy\n\n")
	b.WriteString("volumes:\n  qd-letsencrypt:\n")
	return b.String()
}
