package proxy

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/ersinkoc/SimpleDeploy/internal/config"
	"github.com/ersinkoc/SimpleDeploy/internal/state"
	"github.com/ersinkoc/SimpleDeploy/internal/wizard"
)

// ProxyDir can be overridden for testing. Defaults to config.BaseDir/proxy.
var ProxyDir string

func getProxyDir() string {
	if ProxyDir != "" {
		return ProxyDir
	}
	return config.ProxyDir()
}

func SetupTraefik(ctx context.Context, acmeEmail string) error {
	// Defense-in-depth: init.go validates at input, but the email is
	// interpolated raw into the compose YAML and into a .env file below.
	// Stricter check than the previous regex-only path: state.ValidateEmail
	// also rejects control characters and shell/YAML metacharacters.
	if err := state.ValidateEmail(acmeEmail); err != nil {
		return fmt.Errorf("invalid ACME email: %w", err)
	}

	wizard.Info("Setting up Traefik reverse proxy...")

	if err := osMkdirAll(getProxyDir(), 0755); err != nil {
		return fmt.Errorf("failed to create proxy directory: %w", err)
	}

	composeContent := generateTraefikCompose(acmeEmail)
	composePath := filepath.Join(getProxyDir(), "docker-compose.yml")

	if err := osWriteFile(composePath, []byte(composeContent), 0644); err != nil {
		return fmt.Errorf("failed to write Traefik compose: %w", err)
	}

	// Write .env for ACME email
	envPath := filepath.Join(getProxyDir(), ".env")
	envContent := fmt.Sprintf("ACME_EMAIL=%s\n", acmeEmail)
	// 0600 — the file lives next to compose YAML and contains the operator's
	// email; not a credential per se, but env files are an acknowledged
	// secrets-carrying convention (the per-app .env is also 0600), so we keep
	// the mode tight rather than diverge.
	if err := osWriteFile(envPath, []byte(envContent), 0600); err != nil {
		return fmt.Errorf("failed to write proxy .env: %w", err)
	}

	// Ensure network exists
	if err := dockerCreateNetwork(ctx, "simpledeploy"); err != nil {
		return err
	}

	// Start Traefik
	ctx, cancel := context.WithTimeout(context.Background(), proxySetupTimeout)
	defer cancel()
	cmd := execCommand(ctx, "docker", "compose", "up", "-d")
	cmd.SetDir(getProxyDir())
	cmd.SetStdout(os.Stdout)
	cmd.SetStderr(os.Stderr)
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to start Traefik: %w", err)
	}

	wizard.Success("Traefik reverse proxy started")
	return nil
}

func StopTraefik() error {
	ctx, cancel := context.WithTimeout(context.Background(), proxyExecTimeout)
	defer cancel()
	cmd := exec.CommandContext(ctx, "docker", "compose", "down")
	cmd.Dir = getProxyDir()
	return cmd.Run()
}

func RestartTraefik() error {
	ctx, cancel := context.WithTimeout(context.Background(), proxyExecTimeout)
	defer cancel()
	cmd := exec.CommandContext(ctx, "docker", "compose", "restart")
	cmd.Dir = getProxyDir()
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func generateTraefikCompose(acmeEmail string) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by SimpleDeploy — DO NOT EDIT\n")
	b.WriteString("# Reverse Proxy: Traefik\n\n")
	b.WriteString("networks:\n  simpledeploy:\n    name: simpledeploy\n    external: true\n\n")
	b.WriteString("services:\n  traefik:\n")
	b.WriteString("    image: traefik:v3\n")
	b.WriteString("    container_name: qd-traefik\n")
	b.WriteString("    restart: unless-stopped\n")
	b.WriteString("    command:\n")
	b.WriteString("      - \"--api.dashboard=false\"\n")
	b.WriteString("      - \"--providers.docker=true\"\n")
	b.WriteString("      - \"--providers.docker.exposedbydefault=false\"\n")
	b.WriteString("      - \"--providers.docker.network=simpledeploy\"\n")
	b.WriteString("      - \"--entrypoints.web.address=:80\"\n")
	b.WriteString("      - \"--entrypoints.websecure.address=:443\"\n")
	b.WriteString("      - \"--entrypoints.web.http.redirections.entryPoint.to=websecure\"\n")
	b.WriteString(fmt.Sprintf("      - \"--certificatesresolvers.letsencrypt.acme.email=%s\"\n", acmeEmail))
	b.WriteString("      - \"--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json\"\n")
	b.WriteString("      - \"--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web\"\n")
	b.WriteString("    ports:\n      - \"80:80\"\n      - \"443:443\"\n")
	b.WriteString("    volumes:\n")
	b.WriteString("      - /var/run/docker.sock:/var/run/docker.sock:ro\n")
	b.WriteString("      - qd-letsencrypt:/letsencrypt\n")
	b.WriteString("    networks:\n      - simpledeploy\n\n")
	b.WriteString("volumes:\n  qd-letsencrypt:\n")
	return b.String()
}
